// @flow
export const GET_SPARQL_QUERY = "GET_SPARQL_QUERY";
export const GET_SPARQL_QUERY_FAILURE = "GET_SPARQL_QUERY_FAILURE";
export const GET_SPARQL_QUERY_SUCCESS = "GET_SPARQL_QUERY_SUCCESS";
export const RECEIVE_SPARQL_QUERY = "RECEIVE_SPARQL_QUERY";
export const SET_SPARQL_QUERY = "SET_SPARQL_QUERY";
