// @flow
export const APPLY_ENTITY_GROUP_FILTER = "APPLY_ENTITY_GROUP_FILTER";
export const GET_ENTITY = "GET_ENTITY";
export const GET_ENTITY_FAILURE = "GET_ENTITY_FAILURE";
export const GET_ENTITY_SUCCESS = "GET_ENTITY_SUCCESS";
export const RECEIVE_ENTITY = "RECEIVE_ENTITY";
export const SELECT_ENTITY = "SELECT_ENTITY";
export const UPDATE_ENTITY_DATA = "UPDATE_ENTITY_DATA";
